use serde::{Deserialize, Serialize};

use crate::manifest::ManifestEntryV2;
use crate::path::SyncPath;
use crate::manifest::ManifestV2;
use crate::sync::{ScopeProfileId, SyncMode};

/// Unique identifier for a sync plan, generated by the server.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PlanId(pub String);

/// A computed synchronization plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPlan {
    pub plan_id: PlanId,
    /// Files to transfer (download for pull, upload for push).
    pub transfer: Vec<ManifestEntryV2>,
    /// Paths to delete on the target side (only applied for mirror mode).
    #[serde(default)]
    pub delete: Vec<SyncPath>,
    pub files_total: usize,
    pub bytes_total: u64,
}

/// Request body for `POST /v2/sync/pull-plan`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PullPlanRequest {
    pub profile: ScopeProfileId,
    #[serde(default)]
    pub mode: SyncMode,
    pub target_manifest: ManifestV2,
}

/// Request body for `POST /v2/sync/push-plan`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PushPlanRequest {
    pub profile: ScopeProfileId,
    #[serde(default)]
    pub mode: SyncMode,
    pub source_manifest: ManifestV2,
}

/// Response body for `POST /v2/plans/{plan_id}/commit`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitResponse {
    pub ok: bool,
}
