use serde::{Deserialize, Serialize};

use crate::dataset::DatasetSelection;
use crate::manifest::ManifestEntryV2;
use crate::manifest::ManifestV2;
use crate::path::SyncPath;
use crate::sync::{OverwritePolicy, SyncMode};

/// Unique identifier for a sync plan, generated by the server.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PlanId(pub String);

/// A computed synchronization plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SyncPlan {
    pub plan_id: PlanId,
    pub selection: DatasetSelection,
    /// Files to transfer (download for pull, upload for push).
    pub transfer: Vec<ManifestEntryV2>,
    /// Paths to delete on the target side (only applied for mirror mode).
    #[serde(default)]
    pub delete: Vec<SyncPath>,
    pub files_total: usize,
    pub bytes_total: u64,
}

/// Request body for `POST /v2/sync/pull-plan`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PullPlanRequest {
    #[serde(default)]
    pub mode: SyncMode,
    #[serde(default)]
    pub overwrite_policy: OverwritePolicy,
    pub selection: DatasetSelection,
    pub target_manifest: ManifestV2,
}

/// Request body for `POST /v2/sync/push-plan`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PushPlanRequest {
    #[serde(default)]
    pub mode: SyncMode,
    #[serde(default)]
    pub overwrite_policy: OverwritePolicy,
    pub selection: DatasetSelection,
    pub source_manifest: ManifestV2,
}

/// Response body for `POST /v2/plans/{plan_id}/commit`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitResponse {
    pub ok: bool,
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{PullPlanRequest, PushPlanRequest};
    use crate::sync::OverwritePolicy;

    #[test]
    fn overwrite_policy_defaults_to_exact_when_omitted() {
        let request: PullPlanRequest = serde_json::from_value(json!({
            "selection": { "policy_version": 1, "dataset_ids": [] },
            "target_manifest": { "entries": [] }
        }))
        .expect("pull request without overwrite policy");

        assert_eq!(request.overwrite_policy, OverwritePolicy::Exact);
    }

    #[test]
    fn overwrite_policy_accepts_prefer_newer() {
        let request: PushPlanRequest = serde_json::from_value(json!({
            "overwrite_policy": "prefer-newer",
            "selection": { "policy_version": 1, "dataset_ids": [] },
            "source_manifest": { "entries": [] }
        }))
        .expect("push request with prefer-newer overwrite policy");

        assert_eq!(request.overwrite_policy, OverwritePolicy::PreferNewer);
    }
}
